import pg from 'pg';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
async function run() {
  const c = await pool.connect();
  try {
    // === SERVICE 10: Industrial AI Inspection ===
    let {rows} = await c.query(`SELECT id FROM services WHERE slug='industrial-ai-inspection'`);
    if (rows.length) {
      const id = rows[0].id;
      await c.query(`UPDATE services SET hero_image_url=$1, problem_statement=$2, problem_statement_ar=$3, overview_long=$4, overview_long_ar=$5 WHERE id=$6`, [
        '/uploads/hero_industrial_inspect.png',
        'Manual quality inspection is slow, inconsistent, and cannot scale with production demands. Human inspectors miss up to 30% of defects due to fatigue, while sampling-based approaches leave most products unchecked.',
        'الفحص اليدوي للجودة بطيء وغير متسق ولا يمكن توسيعه مع متطلبات الإنتاج. يفوّت المفتشون البشريون ما يصل إلى ٣٠٪ من العيوب بسبب الإرهاق، بينما الأساليب القائمة على العينات تترك معظم المنتجات دون فحص.',
        'We deploy AI-powered visual inspection systems that examine 100% of production output in real-time. Our computer vision models detect defects invisible to the human eye, classify anomalies by severity, and trigger automated responses.\n\nEvery system is calibrated to your specific products and quality standards, with continuous learning from new defect patterns.',
        'ننشر أنظمة فحص بصري مدعومة بالذكاء الاصطناعي تفحص ١٠٠٪ من الإنتاج في الوقت الفعلي. نماذج الرؤية الحاسوبية لدينا تكشف عيوباً غير مرئية للعين البشرية وتصنف الشذوذ حسب الشدة وتطلق استجابات آلية.\n\nكل نظام مُعاير لمنتجاتك ومعايير الجودة الخاصة بك، مع تعلم مستمر من أنماط العيوب الجديدة.',
        id]);
      const dels = [['Camera & Sensor Setup','إعداد الكاميرات والمستشعرات','Industrial camera selection, mounting, lighting design, and calibration for optimal defect visibility.','اختيار الكاميرات الصناعية والتركيب وتصميم الإضاءة والمعايرة لأقصى رؤية للعيوب.','2-3 weeks'],['Defect Detection Model','نموذج كشف العيوب','Custom CV model trained on your specific products, defect types, and quality thresholds.','نموذج رؤية حاسوبية مخصص مدرب على منتجاتك وأنواع العيوب وعتبات الجودة.','4-6 weeks'],['Real-time Processing Pipeline','خط معالجة لحظي','Edge computing pipeline processing camera feeds at production line speed with sub-50ms latency.','خط حوسبة حافة يعالج تغذيات الكاميرا بسرعة خط الإنتاج مع زمن استجابة أقل من ٥٠ مللي ثانية.','3-4 weeks'],['Quality Dashboard','لوحة معلومات الجودة','Real-time quality monitoring dashboard with defect analytics, trend tracking, and compliance reports.','لوحة مراقبة جودة لحظية مع تحليلات العيوب وتتبع الاتجاهات وتقارير الامتثال.','2-3 weeks'],['Alert & Rejection System','نظام التنبيه والرفض','Automated alerts and physical rejection mechanisms integrated with your production line PLCs.','تنبيهات آلية وآليات رفض فيزيائية متكاملة مع وحدات التحكم المنطقية لخط الإنتاج.','1-2 weeks']];
      for (const d of dels) await c.query(`INSERT INTO service_deliverables (service_id,title,title_ar,description,description_ar,expected_timeline) VALUES ($1,$2,$3,$4,$5,$6)`,[id,...d]);
      const ucs = [['Automotive Parts Inspection','فحص قطع غيار السيارات','Detecting surface defects, dimensional deviations, and assembly errors on automotive components at line speed.','كشف عيوب السطح والانحرافات البعدية وأخطاء التجميع في مكونات السيارات بسرعة خط الإنتاج.','Manufacturing','99.5% defect detection rate','معدل كشف عيوب ٩٩.٥٪'],['Food & Beverage QC','ضبط جودة الأغذية والمشروبات','Detecting contamination, packaging defects, fill level anomalies, and label verification.','كشف التلوث وعيوب التغليف وشذوذ مستوى التعبئة والتحقق من الملصقات.','Manufacturing','100% inspection coverage','تغطية فحص ١٠٠٪'],['Construction Material Testing','اختبار مواد البناء','AI inspection of concrete, steel, and composite materials for structural integrity and compliance.','فحص بالذكاء الاصطناعي للخرسانة والصلب والمواد المركبة للسلامة الهيكلية والامتثال.','Smart Infrastructure','40% reduction in material waste','تقليل ٤٠٪ في هدر المواد']];
      for (const u of ucs) await c.query(`INSERT INTO service_use_cases (service_id,title,title_ar,description,description_ar,industry,business_impact,business_impact_ar) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,...u]);
      const pkgs = [['Discovery','Starting from $5,000','$5,000 - $15,000','Site assessment, feasibility study, and system design proposal.','تقييم الموقع ودراسة الجدوى ومقترح تصميم النظام.',JSON.stringify(['Site Assessment','Feasibility Study','System Design','ROI Analysis']),'2 revision rounds','جولتان من المراجعات','All deliverables transferred.','جميع المخرجات تُنقل للعميل.'],['Implementation','Starting from $30,000','$30,000 - $150,000','Full system deployment including cameras, edge computing, model training, and integration.','نشر كامل للنظام شاملاً الكاميرات والحوسبة الحافة وتدريب النموذج والتكامل.',JSON.stringify(['Camera System','Detection Model','Processing Pipeline','Dashboard','PLC Integration','Documentation']),'90-day support','دعم ٩٠ يوماً','Full IP transfer.','نقل كامل للملكية الفكرية.'],['Retainer','From $3,000/month','$3,000 - $12,000/month','Model retraining, system monitoring, accuracy optimization, and new defect type training.','إعادة تدريب النموذج ومراقبة النظام وتحسين الدقة وتدريب على أنواع عيوب جديدة.',JSON.stringify(['Model Retraining','24/7 Monitoring','Accuracy Reports','Priority Support']),'Priority SLA','اتفاقية خدمة ذات أولوية','All improvements transferred.','جميع التحسينات تُنقل شهرياً.']];
      for (const p of pkgs) await c.query(`INSERT INTO service_pricing_models (service_id,model_type,starting_price,typical_range,scope_summary,scope_summary_ar,deliverables_json,support_terms,support_terms_ar,ip_ownership_notes,ip_ownership_notes_ar,features_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$7)`,[id,...p]);
      const faqs = [['What defect sizes can you detect?','ما أحجام العيوب التي يمكنكم كشفها؟','Our systems detect defects as small as 0.1mm depending on camera resolution and lighting setup. We calibrate to your specific quality thresholds.','تكشف أنظمتنا عيوباً بحجم ٠.١ مم حسب دقة الكاميرا وإعداد الإضاءة. نُعاير وفق عتبات الجودة الخاصة بك.',0],['Does it work with existing production lines?','هل يعمل مع خطوط الإنتاج الحالية؟','Yes. We design non-intrusive installations that integrate with your existing conveyor systems and PLCs without production downtime.','نعم. نصمم تركيبات غير تدخلية تتكامل مع أنظمة النقل ووحدات التحكم الحالية دون توقف الإنتاج.',1],['What happens when a defect is found?','ماذا يحدث عند اكتشاف عيب؟','The system can trigger automated rejection, send alerts to operators, log the defect with images for QC records, and update production analytics dashboards in real-time.','يمكن للنظام تشغيل الرفض الآلي وإرسال تنبيهات للمشغلين وتسجيل العيب بالصور لسجلات الجودة وتحديث لوحات تحليلات الإنتاج لحظياً.',2]];
      for (const f of faqs) await c.query(`INSERT INTO service_faq (service_id,question,question_ar,answer,answer_ar,order_index) VALUES ($1,$2,$3,$4,$5,$6)`,[id,...f]);
      for (const [i,t] of ['YOLOv11','OpenCV','TensorRT','NVIDIA Jetson','Python','ONNX','GStreamer','MQTT'].entries())
        await c.query(`INSERT INTO service_tech_stack (service_id,name,category,order_index) VALUES ($1,$2,'core',$3)`,[id,t,i]);
      const imps = [['Detection Rate','معدل الكشف','99.5%','Defect detection accuracy on trained products.','دقة كشف العيوب على المنتجات المدربة.','efficiency'],['Inspection Speed','سرعة الفحص','<50ms','Per-unit inspection latency at line speed.','زمن فحص الوحدة بسرعة خط الإنتاج.','efficiency'],['Scrap Reduction','تقليل الهدر','45%','Reduction in wasted materials through early detection.','تقليل في المواد المهدرة من خلال الكشف المبكر.','cost_reduction']];
      for (const [i,m] of imps.entries()) await c.query(`INSERT INTO service_impact_metrics (service_id,metric_title,metric_title_ar,metric_value,metric_description,metric_description_ar,impact_category,order_index) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,...m,i]);
      console.log('✅ industrial-ai-inspection seeded');
    }

    // === SERVICE 11: Decision Support Systems ===
    ({rows} = await c.query(`SELECT id FROM services WHERE slug='decision-support-systems'`));
    if (rows.length) {
      const id = rows[0].id;
      await c.query(`UPDATE services SET hero_image_url=$1, problem_statement=$2, problem_statement_ar=$3, overview_long=$4, overview_long_ar=$5 WHERE id=$6`, [
        '/uploads/hero_decision_support.png',
        'Critical business decisions are made with incomplete data, gut instinct, and outdated analysis frameworks. This leads to missed opportunities, unquantified risks, and suboptimal resource allocation across the enterprise.',
        'القرارات التجارية الحرجة تُتخذ ببيانات ناقصة وحدس وأطر تحليل قديمة. يؤدي ذلك إلى فرص ضائعة ومخاطر غير مُقدّرة وتخصيص غير مثالي للموارد عبر المؤسسة.',
        'We build AI-driven decision intelligence platforms that combine predictive modeling, scenario simulation, and risk assessment to help executives make data-backed decisions with confidence.\n\nOur systems integrate with your business data sources to provide real-time decision support with explainable AI outputs that stakeholders can trust.',
        'نبني منصات ذكاء قرار مدعومة بالذكاء الاصطناعي تجمع بين النمذجة التنبؤية ومحاكاة السيناريوهات وتقييم المخاطر لمساعدة المديرين التنفيذيين على اتخاذ قرارات مدعومة بالبيانات بثقة.\n\nتتكامل أنظمتنا مع مصادر بيانات عملك لتوفير دعم قرار لحظي مع مخرجات ذكاء اصطناعي قابلة للتفسير يمكن لأصحاب المصلحة الوثوق بها.',
        id]);
      const dels = [['Decision Framework Design','تصميم إطار القرار','Custom decision framework mapping key business decisions to required data inputs and analytical models.','إطار قرار مخصص يربط القرارات التجارية الرئيسية بالمدخلات البيانية المطلوبة والنماذج التحليلية.','2-3 weeks'],['Predictive Model Suite','مجموعة النماذج التنبؤية','Ensemble of predictive models for revenue forecasting, risk scoring, and demand prediction.','مجموعة من النماذج التنبؤية للتنبؤ بالإيرادات وتقييم المخاطر والتنبؤ بالطلب.','4-6 weeks'],['Scenario Simulator','محاكي السيناريوهات','Interactive tool for modeling what-if scenarios with variable adjustment and outcome visualization.','أداة تفاعلية لنمذجة سيناريوهات ماذا-لو مع تعديل المتغيرات وتصور النتائج.','3-4 weeks'],['Risk Assessment Engine','محرك تقييم المخاطر','Quantitative risk analysis with probability scoring, impact mapping, and mitigation recommendations.','تحليل مخاطر كمي مع تقييم الاحتمالات وخرائط الأثر وتوصيات التخفيف.','3-4 weeks'],['Executive Decision Portal','بوابة القرار التنفيذية','Unified portal presenting decision recommendations with supporting evidence and confidence levels.','بوابة موحدة تقدم توصيات القرار مع الأدلة الداعمة ومستويات الثقة.','2-3 weeks']];
      for (const d of dels) await c.query(`INSERT INTO service_deliverables (service_id,title,title_ar,description,description_ar,expected_timeline) VALUES ($1,$2,$3,$4,$5,$6)`,[id,...d]);
      const ucs = [['Investment Portfolio Optimization','تحسين محفظة الاستثمار','AI-powered portfolio analysis with risk-adjusted return optimization and market scenario modeling.','تحليل محفظة مدعوم بالذكاء الاصطناعي مع تحسين العائد المعدل بالمخاطر ونمذجة سيناريوهات السوق.','Finance','18% improvement in risk-adjusted returns','تحسين ١٨٪ في العوائد المعدلة بالمخاطر'],['Supply Chain Risk Management','إدارة مخاطر سلاسل الإمداد','Predictive supply chain disruption alerts with alternative supplier recommendations and impact scoring.','تنبيهات تنبؤية بتعطل سلاسل الإمداد مع توصيات موردين بديلين وتقييم الأثر.','Logistics & Supply Chain','35% reduction in disruption impact','تقليل ٣٥٪ في أثر التعطيلات'],['Strategic Planning Assistant','مساعد التخطيط الاستراتيجي','AI assistant analyzing market trends, competitive landscape, and growth opportunities for strategic planning.','مساعد ذكي يحلل اتجاهات السوق والمشهد التنافسي وفرص النمو للتخطيط الاستراتيجي.','Enterprise Operations','25% faster strategic decision cycles','تسريع دورات القرار الاستراتيجي ٢٥٪']];
      for (const u of ucs) await c.query(`INSERT INTO service_use_cases (service_id,title,title_ar,description,description_ar,industry,business_impact,business_impact_ar) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,...u]);
      const pkgs = [['Discovery','Starting from $5,000','$5,000 - $15,000','Decision process mapping, data assessment, and DSS architecture proposal.','خرائط عمليات القرار وتقييم البيانات ومقترح بنية نظام دعم القرار.',JSON.stringify(['Decision Mapping','Data Assessment','Architecture Proposal','ROI Projection']),'2 revision rounds','جولتان من المراجعات','All deliverables transferred.','جميع المخرجات تُنقل للعميل.'],['Implementation','Starting from $30,000','$30,000 - $150,000','Full DSS development with predictive models, scenario simulator, and executive portal.','تطوير كامل لنظام دعم القرار مع نماذج تنبؤية ومحاكي سيناريوهات وبوابة تنفيذية.',JSON.stringify(['Predictive Models','Scenario Simulator','Risk Engine','Executive Portal','Integration','Documentation']),'90-day support','دعم ٩٠ يوماً','Full IP transfer.','نقل كامل للملكية الفكرية.'],['Retainer','From $3,500/month','$3,500 - $15,000/month','Model retraining, new decision domains, performance monitoring, and strategic advisory.','إعادة تدريب النماذج ومجالات قرار جديدة ومراقبة الأداء واستشارات استراتيجية.',JSON.stringify(['Model Updates','New Domains','Performance Reviews','Strategic Advisory']),'Priority SLA','اتفاقية خدمة ذات أولوية','All improvements transferred.','جميع التحسينات تُنقل شهرياً.']];
      for (const p of pkgs) await c.query(`INSERT INTO service_pricing_models (service_id,model_type,starting_price,typical_range,scope_summary,scope_summary_ar,deliverables_json,support_terms,support_terms_ar,ip_ownership_notes,ip_ownership_notes_ar,features_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$7)`,[id,...p]);
      const faqs = [['What decisions can the system support?','ما القرارات التي يمكن للنظام دعمها؟','Any data-driven decision including pricing strategy, resource allocation, market entry, investment, risk management, and operational optimization.','أي قرار مبني على البيانات بما في ذلك استراتيجية التسعير وتخصيص الموارد ودخول السوق والاستثمار وإدارة المخاطر وتحسين العمليات.',0],['How does the AI explain its recommendations?','كيف يشرح الذكاء الاصطناعي توصياته؟','We use explainable AI techniques (SHAP, LIME) to show which factors influenced each recommendation, with confidence scores and alternative scenarios.','نستخدم تقنيات الذكاء الاصطناعي القابل للتفسير لإظهار العوامل المؤثرة في كل توصية مع درجات ثقة وسيناريوهات بديلة.',1],['Can it integrate with our existing BI tools?','هل يمكن تكامله مع أدوات ذكاء الأعمال الحالية؟','Yes. Our DSS can feed recommendations directly into your existing dashboards, or operate as a standalone portal with API access for your BI tools.','نعم. يمكن لنظامنا تغذية التوصيات مباشرة في لوحات المعلومات الحالية أو العمل كبوابة مستقلة مع وصول API لأدوات ذكاء الأعمال.',2]];
      for (const f of faqs) await c.query(`INSERT INTO service_faq (service_id,question,question_ar,answer,answer_ar,order_index) VALUES ($1,$2,$3,$4,$5,$6)`,[id,...f]);
      for (const [i,t] of ['Python','scikit-learn','XGBoost','Monte Carlo','React','D3.js','FastAPI','PostgreSQL'].entries())
        await c.query(`INSERT INTO service_tech_stack (service_id,name,category,order_index) VALUES ($1,$2,'core',$3)`,[id,t,i]);
      const imps = [['Decision Accuracy','دقة القرار','85%+','Improvement in decision outcome quality.','تحسين في جودة نتائج القرارات.','efficiency'],['Risk Visibility','رؤية المخاطر','360°','Complete risk landscape visibility.','رؤية شاملة لمشهد المخاطر.','risk_reduction'],['Planning Speed','سرعة التخطيط','3x Faster','Strategic planning cycle acceleration.','تسريع دورة التخطيط الاستراتيجي.','efficiency']];
      for (const [i,m] of imps.entries()) await c.query(`INSERT INTO service_impact_metrics (service_id,metric_title,metric_title_ar,metric_value,metric_description,metric_description_ar,impact_category,order_index) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,...m,i]);
      console.log('✅ decision-support-systems seeded');
    }
    console.log('\n🎉 Services 10-11 done!');
  } finally { c.release(); await pool.end(); }
}
run();
