import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { Link } from "wouter";
import { ArrowRight, CalendarDays, PlayCircle } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTheme } from "@/contexts/ThemeContext";
import { useSEO } from "@/hooks/useSEO";

export default function Courses() {
  const { t, isRTL } = useLanguage();
  const { theme } = useTheme();
  const isLight = theme === "light";
  useSEO({ title: "Courses | Infinity X Academy", description: "Choose live or recorded technology courses from Infinity X Academy.", canonical: "https://infx.space/courses", robots: "index, follow" });
  const formats = [
    { title: t("Learn live, alongside a cohort.", "تعلم مباشرة ضمن دفعة.", "Learn live, alongside a cohort."), description: t("Instructor-led short courses with planned sessions, feedback, and a shared pace.", "دورات قصيرة يقودها مدربون مع جلسات مخططة وملاحظات وإيقاع مشترك.", "Instructor-led short courses with planned sessions and feedback."), label: t("Explore live courses", "استكشف الدورات المباشرة", "Explore live courses"), href: "/courses/live", icon: CalendarDays, tone: "bg-[#071321] text-white" },
    { title: t("Learn on your own schedule.", "تعلم وفق جدولك.", "Learn on your own schedule."), description: t("Recorded courses for focused practice when and where it fits your work.", "دورات مسجلة لممارسة مركزة في الوقت والمكان المناسبين لعملك.", "Recorded courses for focused practice on your schedule."), label: t("Explore recorded courses", "استكشف الدورات المسجلة", "Explore recorded courses"), href: "/courses/recorded", icon: PlayCircle, tone: isLight ? "bg-[#e9f0fa] text-[#102033]" : "bg-white/[.06] text-white" },
  ];
  return <div className={`min-h-screen ${isRTL ? "rtl" : "ltr"} ${isLight ? "bg-[#fdfcf9] text-[#102033]" : "bg-[#06101f] text-white"}`} dir={isRTL ? "rtl" : "ltr"}><Navigation /><main><section className="mx-auto max-w-7xl px-6 pb-16 pt-32 lg:px-8 lg:pb-24"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#165dcc]">{t("Infinity X Academy", "أكاديمية إنفينيتي إكس", "Infinity X Academy")}</p><h1 className={`mt-6 text-5xl font-extrabold tracking-[-.065em] sm:text-6xl ${isLight ? "text-slate-950" : "text-white"}`}>{t("Choose the learning experience that fits your work.", "اختر تجربة التعلم التي تناسب عملك.", "Choose the learning experience that fits your work.")}</h1><p className={`mt-7 max-w-2xl text-lg leading-8 ${isLight ? "text-slate-600" : "text-slate-300"}`}>{t("Both formats are designed around practical technology work. The difference is how you prefer to learn.", "كلا النمطين مصممان حول العمل التقني العملي. والفرق هو كيف تفضل أن تتعلم.", "Both formats are designed around practical technology work.")}</p></div></section><section className="mx-auto grid max-w-7xl gap-px px-6 pb-20 sm:grid-cols-2 lg:px-8 lg:pb-28">{formats.map((format) => <Link key={format.href} href={format.href} className={`group min-h-[360px] p-7 sm:p-10 ${format.tone} ${format.href === "/courses/live" ? "academy-dark-panel" : ""}`}><format.icon className="h-8 w-8 text-[#165dcc]" /><h2 className="mt-14 max-w-sm text-3xl font-extrabold tracking-[-.045em]">{format.title}</h2><p className={`mt-5 max-w-sm text-sm leading-7 ${format.tone.includes("#071321") ? "text-slate-300" : isLight ? "text-slate-600" : "text-slate-300"}`}>{format.description}</p><span className="mt-10 inline-flex items-center gap-2 text-sm font-bold text-[#165dcc] group-hover:underline">{format.label}<ArrowRight className={`h-4 w-4 ${isRTL ? "rotate-180" : ""}`} /></span></Link>)}</section><section className={`border-y py-14 ${isLight ? "border-slate-200 bg-[#f2f5f8]" : "border-white/10 bg-white/[.03]"}`}><div className="mx-auto max-w-7xl px-6 lg:px-8"><Link href="/programs" className="inline-flex items-center gap-2 text-sm font-bold text-[#165dcc]">{t("Looking for a longer program? Explore Academy programs.", "تبحث عن برنامج أطول؟ استكشف برامج الأكاديمية.", "Looking for a longer program? Explore Academy programs.")}<ArrowRight className={`h-4 w-4 ${isRTL ? "rotate-180" : ""}`} /></Link></div></section></main><Footer /></div>;
}
