import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { useLanguage } from "@/contexts/LanguageContext";
import { useSEO } from "@/hooks/useSEO";
import { ArrowLeft, ArrowRight, ArrowUpRight, Award, ChevronDown, Clock3, ExternalLink, Layers, Loader2, Video } from "lucide-react";

export default function ProgramDetails() {
  const [, params] = useRoute("/program/:id");
  const programId = params?.id || "";
  const { lang, isRTL, t } = useLanguage();
  const { data: programData, isLoading } = trpc.admin.getProgramComplete.useQuery({ id: programId }, { enabled: Boolean(programId) });
  const program = programData?.info as any;
  const modules = (programData?.modules || []) as any[];
  const copy = (en?: string, ar?: string, fallback = "") => t(en || fallback, ar || en || fallback, fallback || en || "");
  const appUrl = program ? `/apply?programId=${program.id}&programName=${encodeURIComponent(program.title)}` : "/apply";
  const skills = String(program?.skills || "").split(",").map((skill) => skill.trim()).filter(Boolean);
  const currency = (value: unknown, code: string) => Number(value) > 0 ? new Intl.NumberFormat(lang === "ar" ? "ar-EG" : "en-EG", { style: "currency", currency: code, maximumFractionDigits: 0 }).format(Number(value)) : "";
  const tuition = [currency(program?.priceEgp, "EGP"), currency(program?.priceUsd, "USD")].filter(Boolean).join(" / ") || copy("Contact for tuition", "تواصل لمعرفة الرسوم", "Contact for tuition");
  useSEO({ title: program?.title ? `${program.title} | Infinity X Academy` : "Academy Program | Infinity X", description: program?.description || "Explore a practical technology program from Infinity X Academy.", canonical: `https://infx.space/program/${programId}`, robots: isLoading ? undefined : program ? "index, follow" : "noindex, follow" });

  if (isLoading) return <div className="grid min-h-screen place-items-center bg-[#091522] text-white"><Loader2 className="h-8 w-8 animate-spin text-[#7db2ff]" /></div>;
  if (!program) return <div className={`ix-page grid min-h-screen place-items-center px-6 text-center ${isRTL ? "rtl" : "ltr"}`} dir={isRTL ? "rtl" : "ltr"}><div><Award className="mx-auto h-10 w-10 text-[#1268e5]" /><h1 className="ix-display mt-6 text-4xl font-bold">{copy("Program not found.", "البرنامج غير موجود.")}</h1><p className="mx-auto mt-4 max-w-md text-sm leading-7" style={{ color: "var(--ix-text-secondary)" }}>{copy("This program may no longer be available. Explore the current Academy offering.", "قد لا يكون هذا البرنامج متاحاً حالياً. استكشف عروض الأكاديمية الحالية.")}</p><Link href="/programs" className="ix-button ix-button-primary mt-8">{copy("Explore programs", "استكشف البرامج")}<ArrowRight className={`h-4 w-4 ${isRTL ? "rotate-180" : ""}`} /></Link></div></div>;

  const facts = [{ label: copy("Discipline", "التخصص"), value: copy(program.category, program.categoryAr, copy("Academy program", "برنامج أكاديمي")), icon: Layers }, { label: copy("Duration", "المدة"), value: program.duration || copy("See curriculum", "راجع المنهج"), icon: Clock3 }, { label: copy("Format", "النمط"), value: program.deliveryMode || copy("See program details", "راجع تفاصيل البرنامج"), icon: Video }, { label: copy("Tuition", "الرسوم"), value: tuition, icon: Award }];
  return <div className={`ix-page ${isRTL ? "rtl" : "ltr"}`} dir={isRTL ? "rtl" : "ltr"}><Navigation /><main>
    <section className="ix-dark-surface bg-[#091522] pt-28 text-white sm:pt-32"><div className="ix-shell grid gap-10 pb-16 lg:grid-cols-[1.05fr_.95fr] lg:items-end lg:pb-20"><div><Link href="/programs" className="inline-flex items-center gap-2 text-sm font-semibold text-[#b9c8d1] hover:text-white"><ArrowLeft className={`h-4 w-4 ${isRTL ? "rotate-180" : ""}`} />{copy("All programs", "كل البرامج")}</Link><p className="ix-eyebrow mt-12 text-[#b9efd5]">{copy("Infinity X Academy program", "برنامج أكاديمية إنفينيتي إكس")}</p><h1 className="ix-display mt-6 max-w-3xl text-5xl font-bold sm:text-6xl">{copy(program.title, program.titleAr, program.title)}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#b9c8d1]">{copy(program.description, program.descriptionAr, program.description)}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={appUrl} className="ix-button ix-button-primary">{copy("Apply to this program", "قدم طلباً لهذا البرنامج")}<ArrowUpRight className="h-4 w-4" /></Link><a href="#curriculum" className="ix-button ix-button-secondary ix-button-dark">{copy("View curriculum", "عرض المنهج")}</a></div></div><div className="relative min-h-[340px] overflow-hidden border border-white/15 bg-[#0d1b28]">{program.imageUrl ? <img src={program.imageUrl} alt={copy(program.title, program.titleAr, program.title)} className="absolute inset-0 h-full w-full object-cover opacity-85" loading="eager" /> : <div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(125,178,255,.22)_1px,transparent_1px),linear-gradient(45deg,rgba(125,178,255,.12)_1px,transparent_1px)] bg-[size:30px_30px]" />}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#07111b] via-[#07111b]/70 to-transparent p-7 pt-24"><p className="ix-eyebrow text-[#7db2ff]">{copy("Project-based learning", "تعلم قائم على المشاريع")}</p><p className="mt-3 max-w-md text-2xl font-bold tracking-[-.035em]">{copy("A structured path from guided practice to applied work.", "مسار منظم من الممارسة الموجهة إلى العمل التطبيقي.")}</p></div></div></div></section>
    <section className="border-b" style={{ borderColor: "var(--ix-border)" }}><div className="ix-shell"><dl className="grid border-s sm:grid-cols-2 lg:grid-cols-4" style={{ borderColor: "var(--ix-border)" }}>{facts.map(({ label, value, icon: Icon }) => <div key={label} className="border-b p-6 lg:border-e lg:last:border-e-0" style={{ borderColor: "var(--ix-border)" }}><dt className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-[#71808b]"><Icon className="h-3.5 w-3.5 text-[#1268e5]" />{label}</dt><dd className="mt-3 text-sm font-bold leading-6">{value}</dd></div>)}</dl></div></section>
    {(skills.length > 0 || modules.length > 0) && <section className="border-b" style={{ borderColor: "var(--ix-border)", background: "var(--ix-surface-muted)" }}><div className="ix-shell grid gap-10 py-16 lg:grid-cols-[.8fr_1.2fr] lg:py-20"><div><p className="ix-kicker">{copy("Program outcome", "مخرجات البرنامج")}</p><h2 className="ix-display mt-5 text-4xl font-bold">{copy("Build evidence of what you can do.", "ابنِ دليلاً على ما يمكنك إنجازه.")}</h2><p className="mt-5 max-w-md text-base leading-7" style={{ color: "var(--ix-text-secondary)" }}>{copy("The program is structured around practical learning rather than an undirected content library.", "صُمم البرنامج حول التعلم العملي بدلاً من مكتبة محتوى غير موجهة.")}</p></div><div>{skills.length > 0 && <div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#71808b]">{copy("Skills covered", "المهارات التي يغطيها البرنامج")}</p><div className="mt-5 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="border bg-[var(--ix-surface)] px-3 py-2 text-sm font-semibold" style={{ borderColor: "var(--ix-border)" }}>{skill}</span>)}</div></div>}{modules.length > 0 && <div className="mt-10 border-t pt-8" style={{ borderColor: "var(--ix-border)" }}><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#71808b]">{copy("Learning design", "تصميم التعلم")}</p><p className="mt-3 text-sm leading-7" style={{ color: "var(--ix-text-secondary)" }}>{copy(`${modules.length} structured module${modules.length === 1 ? "" : "s"} with linked course work.`, `${modules.length} وحدة منظمة مرتبطة بعمل المقررات.`)}</p></div>}</div></div></section>}
    <section id="curriculum" className="ix-section"><div className="ix-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="ix-kicker">{copy("Curriculum", "المنهج")}</p><h2 className="ix-display mt-5 text-4xl font-bold">{copy("A route through the work, not a wall of content.", "مسار خلال العمل، وليس جداراً من المحتوى.")}</h2></div><div className="border-t" style={{ borderColor: "var(--ix-border)" }}>{modules.length === 0 ? <div className="py-12 text-sm leading-7" style={{ color: "var(--ix-text-secondary)" }}>{copy("Curriculum details are being prepared for this program.", "يجري إعداد تفاصيل المنهج لهذا البرنامج.")}</div> : modules.map((module, index) => <details key={module.id} open={index === 0} className="group border-b" style={{ borderColor: "var(--ix-border)" }}><summary className="flex list-none items-center justify-between gap-5 py-6 marker:content-none"><div className="grid gap-3 sm:grid-cols-[58px_1fr]"><span className="text-sm font-bold text-[#1268e5]">{String(index + 1).padStart(2, "0")}</span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#71808b]">{copy("Module", "وحدة")} {index + 1}{module.duration ? ` · ${module.duration}` : ""}</p><h3 className="mt-2 text-xl font-bold">{copy(module.title, module.titleAr, module.title)}</h3>{module.description && <p className="mt-2 max-w-xl text-sm leading-6" style={{ color: "var(--ix-text-secondary)" }}>{copy(module.description, module.descriptionAr, module.description)}</p>}</div></div><ChevronDown className="h-5 w-5 shrink-0 text-[#1268e5] transition-transform group-open:rotate-180" /></summary><div className="pb-7 ps-0 sm:ps-[58px]"><div className="border-s ps-5" style={{ borderColor: "var(--ix-border)" }}>{!module.courses?.length ? <p className="text-sm" style={{ color: "var(--ix-text-secondary)" }}>{copy("Course work is being prepared for this module.", "يجري إعداد عمل المقررات لهذه الوحدة.")}</p> : <ul className="space-y-4">{module.courses.map((course: any) => <li key={course.junctionId || course.id} className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold">{copy(course.title, course.titleAr, course.title)}</p><p className="mt-1 text-xs" style={{ color: "var(--ix-text-muted)" }}>{[course.duration, course.level, course.courseType].filter(Boolean).join(" · ")}</p></div>{course.courseLink && <a href={course.courseLink} target="_blank" rel="noreferrer" className="ix-link inline-flex items-center gap-1 text-xs">{copy("View syllabus", "عرض المنهج")}<ExternalLink className="h-3.5 w-3.5" /></a>}</li>)}</ul>}</div></div></details>)}</div></div></section>
    <section className="ix-dark-surface bg-[#091522] text-white"><div className="ix-shell grid gap-8 py-16 sm:grid-cols-[1.35fr_.65fr] sm:items-end"><div><p className="ix-eyebrow text-[#7db2ff]">{copy("Application", "التقديم")}</p><h2 className="ix-display mt-5 max-w-2xl text-4xl font-bold">{copy("Ready to turn interest into practical work?", "هل أنت مستعد لتحويل الاهتمام إلى عمل عملي؟")}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#b9c8d1]">{copy("Submit your details and the admissions team will review your application.", "أرسل بياناتك وسيراجع فريق القبول طلبك.")}</p></div><Link href={appUrl} className="ix-button ix-button-primary w-full sm:w-auto">{copy("Apply to this program", "قدم طلباً لهذا البرنامج")}<ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </main><Footer /></div>;
}
